### ISSUE TITLE
Sample build.gradle

### ISSUE THREAD

**Issue by amatot** [TanVD/kosogor#10]
I am new to gradle and was wondering if you could provide some examples on how to use this plugin (sample build.gradle. Specifically I am trying to figure out how to pass parameters to the tasks (like -var and -var-file).

**Comment by TanVD** [comment]
There was an example of how to setup terraform plugin with groovy: 
```
import tanvd.kosogor.terraform.*
import java.util.*

plugins {
    id "tanvd.kosogor.terraform" version "1.0.0"
}

TerraformDslKt.terraform(this.project) { dsl ->
    dsl.config { conf ->
        conf.tfVersion = "0.12.2"
        conf.awsProvider = "1.60.0"
        conf.awsRegion = "eu-west-1"
        conf.awsProfile = "default"
    }

    dsl.root("example", file("terraform"), false, new LinkedHashSet())
}
```
from https://github.com/TanVD/kosogor/issues/1

**Comment by TanVD** [comment]
But in general I would not recommend to use Groovy with kosogor :) It was designed for `kts`
