### ISSUE TITLE
Is it possible to publish to GitHub Packages with this?

### ISSUE THREAD

**Issue by yttrian** [TanVD/kosogor#17]
Hello, I was wondering if it is possible to configure `publishJar` to work with GitHub Packages. I spent a while trying to figure it out with no luck so I thought it'd be best to ask.

Thank you.

https://docs.github.com/en/packages/guides/configuring-gradle-for-use-with-github-packages

**Comment by yttrian** [comment]
Seem to have gotten it working with:

```kts
publishJar {
    enablePublication = true
}

publishing {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/<username>/<repo>")
            credentials {
                username = System.getenv("USERNAME")
                password = System.getenv("TOKEN")
            }
        }
    }
}
```

**Comment by TanVD** [comment]
Hey, still I would probably add support in next release :)
