### ISSUE TITLE
Support for terraform fmt 

### ISSUE THREAD

**Issue by stijndehaes** [TanVD/kosogor#9]
It would be nice to have support for terraform fmt. 
I would like the use terraform fmt -check in CI/CD systems and without it on developers laptops.
Are you open to this change. I am willing to give it a try myself and submit a PR but wanted to make sure it would be accepted.

**Comment by TanVD** [comment]
Hi! After review and changes we will definitely merge this PR.
Just note, that `fmt` should be optional functionality, as you've mentioned it should be possible to disable it for local development :)

**Comment by TanVD** [comment]
Waiting for PR :)
